version: '3'
services:
  web:
    build:
      context: ./web
    platform: linux/amd64
    ports:
      - "3000:3000"
    env_file:
      - .env

  api:
    build:
      context: ./fabflix
    platform: linux/amd64
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  mysql-data:
