ALTER TABLE movies
    MODIFY COLUMN id VARCHAR(50)
;

ALTER TABLE stars
    MODIFY COLUMN id VARCHAR(50)
;

ALTER TABLE stars_in_movies
    MODIFY COLUMN starId VARCHAR(50)
;

ALTER TABLE stars_in_movies
    MODIFY COLUMN movieId VARCHAR(50)
;

ALTER TABLE genres_in_movies
    MODIFY COLUMN movieId VARCHAR(50)
;