---
apiVersion: v1
kind: Service
metadata:
  name: mysql-read-balancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-0b5deea23007c0579
    service.beta.kubernetes.io/aws-load-balancer-type: nlb

spec:
  selector:
    app.kubernetes.io/name: mysql # Target pods with label app: my-app

  ports:
    - port: 3306 # Service port (can be different from pod port)
      targetPort: 3306 # Port on which pods are listening
  type: LoadBalancer # Internal load balancer
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: Deployment
metadata:
  name: fabflix
  labels:
    app: fabflix
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fabflix
  template: # Attributes for each pod in the deployment
    metadata:
      labels:
        app: fabflix
    spec:
      containers:
        - name: fabflix
          image: nginx:1.14.2
          ports:
            - containerPort: 8080
