version: '3.3'
services:
#  fabflix:
#    build: .
#    ports:
#      - '8081:8080'
#    container_name: fabflix
  db:
    image: mysql:8
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'moviedb'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
    volumes:
      - ./db:/docker-entrypoint-initdb.d